# Write your MySQL query statement below

SELECT
  D.NAME AS Department
  , E.NAME AS Employee
  , E.SALARY AS Salary
FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
WHERE (D.ID, E.SALARY) IN (SELECT departmentid, MAX(SALARY) AS SALARY FROM EMPLOYEE GROUP BY DEPARTMENTID)

