# # Write your MySQL query statement below

SELECT
    VISITED_ON AS visited_on
    , (SELECT SUM(AMOUNT) FROM CUSTOMER WHERE VISITED_ON BETWEEN DATE_SUB(A.VISITED_ON, INTERVAL 6 DAY) AND A.VISITED_ON) AS amount
    , ROUND((SELECT SUM(AMOUNT)/7 FROM CUSTOMER WHERE VISITED_ON BETWEEN DATE_SUB(A.VISITED_ON, INTERVAL 6 DAY) AND A.VISITED_ON), 2) AS average_amount
FROM
(
    -- 1. 겹치는 일자를 group by 로 선 계산
    SELECT
        VISITED_ON
        , SUM(AMOUNT) AS AMOUNT
    FROM CUSTOMER
    GROUP BY VISITED_ON
) A
WHERE A.VISITED_ON >= (SELECT DATE_ADD(MIN(VISITED_ON), INTERVAL 6 DAY) FROM CUSTOMER)
ORDER BY VISITED_ON