# Write your MySQL query statement below

SELECT
 EMPLOYEE_ID
FROM EMPLOYEES E
WHERE E.SALARY < 30000
AND MANAGER_ID IS NOT NULL
AND NOT EXISTS
  ( 
    SELECT 1 FROM EMPLOYEES E1 WHERE E1.EMPLOYEE_ID = E.MANAGER_ID
  )
ORDER BY EMPLOYEE_ID