# Write your MySQL query statement below

SELECT
  P.PRODUCT_ID
  , P.PRODUCT_NAME
FROM PRODUCT P
WHERE EXISTS (
  SELECT 1 
  FROM SALES S
  WHERE P.PRODUCT_ID = S.PRODUCT_ID
  AND S.SALE_DATE BETWEEN DATE_FORMAT('2019-01-01', '%Y-%m-%d') AND DATE_FORMAT('2019-03-31', '%Y-%m-%d')
)
AND NOT EXISTS (
  SELECT 1
  FROM SALES S
  WHERE P.PRODUCT_ID = S.PRODUCT_ID
  AND (S.SALE_DATE < DATE_FORMAT('2019-01-01', '%Y-%m-%d') OR S.SALE_DATE > DATE_FORMAT('2019-03-31', '%Y-%m-%d'))
)