# Write your MySQL query statement below

SELECT
    ACTOR_ID
    , DIRECTOR_ID
FROM ACTORDIRECTOR
GROUP BY ACTOR_ID, DIRECTOR_ID
HAVING COUNT(ACTOR_ID) = COUNT(DIRECTOR_ID) AND COUNT(ACTOR_ID) >= 3 AND COUNT(DIRECTOR_ID) >= 3