# Write your MySQL query statement below

SELECT 
S.STUDENT_ID AS student_id
, S.STUDENT_NAME AS student_name
, B.SUBJECT_NAME AS subject_name
, COUNT(E.STUDENT_ID) AS attended_exams
FROM STUDENTS S 
CROSS JOIN SUBJECTS B
LEFT OUTER JOIN EXAMINATIONS E ON S.STUDENT_ID = E.STUDENT_ID AND B.SUBJECT_NAME = E.SUBJECT_NAME
GROUP BY S.STUDENT_ID, S.STUDENT_NAME, B.SUBJECT_NAME
ORDER BY STUDENT_ID, SUBJECT_NAME