# Write your MySQL query statement below

SELECT
    U.NAME AS name
    , SUM(T.AMOUNT) AS balance
FROM USERS U INNER JOIN TRANSACTIONS T ON U.ACCOUNT = T.ACCOUNT
GROUP BY T.ACCOUNT
HAVING SUM(T.AMOUNT) > 10000
