
#SELECT COUNT(1) FROM ACTIVITY GROUP BY PLAYER_ID

SELECT 
    ROUND(COUNT(PLAYER_ID)/(SELECT COUNT(DISTINCT(PLAYER_ID)) FROM ACTIVITY), 2) AS fraction
FROM ACTIVITY
WHERE (PLAYER_ID, EVENT_DATE)
IN
(
    SELECT
        PLAYER_ID
        , DATE_ADD(MIN(EVENT_DATE), INTERVAL 1 DAY)
    FROM ACTIVITY
    GROUP BY PLAYER_ID
)
