# Write your MySQL query statement below

SELECT 
    E.EMPLOYEE_ID
FROM EMPLOYEES E LEFT OUTER JOIN SALARIES S ON E.EMPLOYEE_ID = S.EMPLOYEE_ID
WHERE E.NAME IS NULL OR S.SALARY IS NULL
UNION ALL
SELECT
    S.EMPLOYEE_ID
FROM EMPLOYEES E RIGHT OUTER JOIN SALARIES S ON E.EMPLOYEE_ID = S.EMPLOYEE_ID
WHERE E.NAME IS NULL OR S.SALARY IS NULL
ORDER BY EMPLOYEE_ID