# Write your MySQL query statement below
SELECT
ROUND((AVG(IF(ORDER_DATE=CUSTOMER_PREF_DELIVERY_DATE, 1, 0))) * 100, 2) AS immediate_percentage
FROM
DELIVERY
WHERE (CUSTOMER_ID, ORDER_DATE)
IN
(SELECT
    CUSTOMER_ID
    , MIN(ORDER_DATE) AS ORDER_DATE
FROM DELIVERY 
GROUP BY CUSTOMER_ID)
