# Write your MySQL query statement below

SELECT
    P.PRODUCT_NAME
    , SUM(UNIT) AS UNIT
FROM PRODUCTS P 
INNER JOIN ORDERS O 
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(O.ORDER_DATE, '%Y-%m') = '2020-02'
GROUP BY P.PRODUCT_ID
HAVING UNIT >= 100
