# Write your MySQL query statement below

SELECT 
    P.PROJECT_ID AS project_id
    , ROUND(AVG(E.EXPERIENCE_YEARS), 2) AS average_years
FROM PROJECT P INNER JOIN EMPLOYEE E 
ON P.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY P.PROJECT_ID