# Write your MySQL query statement below

SELECT
    USER_ID, MAX(TIME_STAMP) AS LAST_STAMP
FROM LOGINS
WHERE (USER_ID, TIME_STAMP) IN
(
    SELECT 
        USER_ID, TIME_STAMP
    FROM LOGINS 
    GROUP BY USER_ID, TIME_STAMP
    HAVING DATE_FORMAT(TIME_STAMP, '%Y') = '2020'
)
GROUP BY USER_ID